# CONFIG_ZMK_KEYBOARD_NAME="Tomahawk44"
# CONFIG_USB_DEVICE_MANUFACTURER="Tomahawk44"

# Uncomment the following line to enable deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_IDLE_TIMEOUT=180000

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# CONFIG_BT_CTLR_PHY_2M=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y

# Display Configuration
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# Single-color backlight
CONFIG_ZMK_BACKLIGHT=n
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_USB=y

# RGB backlight / underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=60
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=0
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=100
# CONFIG_WS2812_STRIP=y # Deprecated

# Battery/BLE status indications on the RGB underglow strip
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=n
CONFIG_RGBLED_WIDGET_BOOT_SHOW_BATTERY=n
CONFIG_RGBLED_WIDGET_BOOT_SHOW_CONNECTIVITY=y
CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=3000
CONFIG_RGBLED_WIDGET_CONN_STATUS_PIXEL=y
CONFIG_RGBLED_WIDGET_CONN_STATUS_PIXEL_INDEX=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=4
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=4
CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=3000
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXELS=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=y
CONFIG_RGBLED_WIDGET_LAYER_BLINK_MS=3000

# Enable 350MA charger current for large batteries
CONFIG_BOARD_MIKOTO_CHARGER_CURRENT_350MA=y

# Split Bluetooth Synchronization Settings
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=n
