# The right half can only report its own battery status.
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_SELF=y
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_0=11
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_1=10
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_2=9
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_3=8
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_4=7
