# The left half is the split central, so it can show both local and peripheral battery status.
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_PERIPHERALS=y
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_0=6
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_1=7
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_2=8
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_3=9
CONFIG_RGBLED_WIDGET_BATTERY_STATUS_PIXEL_4=10
